// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8R3ttlXOVB6loEsBGNBnbkZX0ZyyAsPg',
    appId: '1:146298128247:web:30e968b07e74183f518372',
    messagingSenderId: '146298128247',
    projectId: 'todo-app-83ea9',
    authDomain: 'todo-app-83ea9.firebaseapp.com',
    storageBucket: 'todo-app-83ea9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5MfDuw-pHTQ1_428jyymf1_JOEYjIHoU',
    appId: '1:146298128247:android:5f36f007c01dd22e518372',
    messagingSenderId: '146298128247',
    projectId: 'todo-app-83ea9',
    storageBucket: 'todo-app-83ea9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsGbgLfvTikI795JODu73_bQZ6RWjT0Gs',
    appId: '1:146298128247:ios:1784ff4adc1eb3ae518372',
    messagingSenderId: '146298128247',
    projectId: 'todo-app-83ea9',
    storageBucket: 'todo-app-83ea9.firebasestorage.app',
    androidClientId: '146298128247-i2463pj1011qr4k1nfnrc3dsh7upb5o3.apps.googleusercontent.com',
    iosClientId: '146298128247-vpr94uhpn0aig3t3ot8ov4qor0bpdk03.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsGbgLfvTikI795JODu73_bQZ6RWjT0Gs',
    appId: '1:146298128247:ios:1784ff4adc1eb3ae518372',
    messagingSenderId: '146298128247',
    projectId: 'todo-app-83ea9',
    storageBucket: 'todo-app-83ea9.firebasestorage.app',
    androidClientId: '146298128247-i2463pj1011qr4k1nfnrc3dsh7upb5o3.apps.googleusercontent.com',
    iosClientId: '146298128247-vpr94uhpn0aig3t3ot8ov4qor0bpdk03.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8R3ttlXOVB6loEsBGNBnbkZX0ZyyAsPg',
    appId: '1:146298128247:web:1f315c2bba436260518372',
    messagingSenderId: '146298128247',
    projectId: 'todo-app-83ea9',
    authDomain: 'todo-app-83ea9.firebaseapp.com',
    storageBucket: 'todo-app-83ea9.firebasestorage.app',
  );

}